name: hemvision

services:
  backend:
    image: mrtsstlrs/hemvision-backend:latest
    build: ./backend
    ports:
      - "8000:8000"
    restart: on-failure

  frontend:
    image: mrtsstlrs/hemvision-frontend:latest
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: "http://localhost:8000/api" # url backend api для фронтенда
    depends_on:
      - backend
    restart: on-failure