name: hemvision

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/app/
      - ./model/rt-detr-x.pt:/app/last.pt
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      # URL вашего API как видит фронтенд
      VITE_API_URL: "http://localhost:8000/api"
    depends_on:
      - backend